security:
    encoders:
        App\Entity\User:
            algorithm:  bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_EDIT:        ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_EDIT]

    providers:
        database_users:
            entity: { class: App\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #pattern: ^/
            anonymous: true
            logout:
                path: app_logout

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

    access_control:
      - { path: ^/admin, roles: ROLE_SUPER_ADMIN }