version: '3.2'

services:
  php:
    image: quay.io/api-platform/php
    build:
      context: ./
      cache_from:
        - quay.io/api-platform/php
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./:/srv/api:rw,consistent
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    ports:
      - "127.0.0.1:9090:9000"

  nginx:
    image: quay.io/api-platform/nginx
    build:
      context: ./
      dockerfile: Dockerfile.nginx
      cache_from:
        - quay.io/api-platform/nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro,consistent
    ports:
      - "8080:80"

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=lmdpe
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db-data: {}
